Fj 2024 lesson 8
Dimes01/T-Homework-1 pull request #5
Opened 2024-10-09 18:52 UTC by Dimes01

2024-10-13 16:02 UTC, SHvatov requested changes
@Dimes01 👍, но пару комментариев все-таки

2024-10-13 16:02 UTC, SHvatov commented on homework8/src/main/java/com/example/tinkoff/Homework8Application.java
> +	public static void main(String[] args) {
Есть ощущение, что что-то не так с табами. Уж больно они большие)

2024-10-13 16:02 UTC, SHvatov commented on homework8/src/main/java/com/example/tinkoff/configurations/CacheConfiguration.java
> +        var executor = Executors.newScheduledThreadPool(1);
Оу ноу, бедный экзекутор, который никогда не будет правильно завершен) Давай лучше через `Scheduled` в этом же классе)

2024-10-13 16:02 UTC, SHvatov commented on homework8/src/main/java/com/example/tinkoff/controllers/CurrenciesController.java
> +    public record ErrorMessage(String message, int code) {}
Давай вынесем в отдельный файл

2024-10-13 16:02 UTC, SHvatov commented on homework8/src/main/java/com/example/tinkoff/controllers/CurrenciesController.java
> +    public record ErrorMessage(String message, int code) {}
А, ну или я понял замысел. Тогда стоит все, что касается обработки исключений вынести в отдельный класс и пометить его как `ControllerAdvice`. И оно в такой конфигурации вообще работает?)

2024-10-13 16:02 UTC, SHvatov commented on homework8/src/main/java/com/example/tinkoff/controllers/CurrenciesController.java
> +            message = "Amount must be positive integer";
Это можно прописать в самой аннотации, чтобы такие проверки и приседания каждый раз не делать)

2024-10-13 16:02 UTC, SHvatov commented on homework8/src/main/java/com/example/tinkoff/services/ValuteService.java
> +        return currencyTo.getValue() / (currencyFrom.getValue() * amount);
1. зачем публик?
2. проверочки на нули не хватает
3. для хранения деняк советую использовать `BigDecimal`, чтобы копеечки не потерять

2024-10-13 16:02 UTC, SHvatov commented on homework8/src/main/resources/api-docs.yaml
> +openapi: 3.0.1
:fire:, но я бы рекомендовал воспользовать автогенерацией через свагер и спринг-док)

2024-10-13 16:02 UTC, SHvatov commented on homework8/src/test/java/com/example/tinkoff/controllers/CurrenciesControllerTest.java
> +    // и CurrencyNotFoundException, хотя в конфиге в application.yml они вроде как исключены (поле ignoreExceptions).
Вероятнее всего конфиг просто не подтягивается. Попробуй прописать их тут через `TestPropertySource` и посмотреть.

2024-10-20 10:49 UTC, Dimes01 commented on homework8/src/main/java/com/example/tinkoff/services/ValuteService.java
> +        return currencyTo.getValue() / (currencyFrom.getValue() * amount);
1. используется в контроллере в эндпоинте `/currencies/convert` 
2. добавил
3. исправил

2024-10-20 12:38 UTC, Dimes01 commented on homework8/src/main/java/com/example/tinkoff/controllers/CurrenciesController.java
> +    public record ErrorMessage(String message, int code) {}
Ну ExceptionHandler-ы вроде срабатывают, но не те, которые надо, из-за CircuitBreaker в ValuteService))

2024-10-20 12:47 UTC, Dimes01 commented on homework8/src/test/java/com/example/tinkoff/controllers/CurrenciesControllerTest.java
> +    // и CurrencyNotFoundException, хотя в конфиге в application.yml они вроде как исключены (поле ignoreExceptions).
Посмотрел, ничего не понял. Попытался создать бин в [CircuitBreakerConfiguration](homework8/src/main/java/com/example/tinkoff/configurations/CircuitBreakerConfiguration.java), но и это не дало результатов

2024-11-04 15:27 UTC, SHvatov commented on homework8/src/test/java/com/example/tinkoff/controllers/CurrenciesControllerTest.java
> +    // и CurrencyNotFoundException, хотя в конфиге в application.yml они вроде как исключены (поле ignoreExceptions).
Штош поделать...

2024-11-04 15:27 UTC, SHvatov approved these changes
@Dimes01 👌

2024-11-04 15:50 UTC, merged